'use strict'

export const SET_BITRATE = 'SET BITRATE'
export const SET_RESOLUTION = 'SET RESOLUTION'
export const SET_FRAMERATE = 'SET FRAMERATE'
export const SET_BPP = 'SET BPP'
export const SET_BPI = 'SET BPI'
export const SET_MONITOR = 'SET MONITOR'
export const SET_TARGET = 'SET TARGET'
export const SET_SETTINGS = 'SET SETTINGS'
